// Buyer seed data for marketplace
export const buyerSeedData = [
  // Nairobi Region
  {
    businessName: "Wangari Organics",
    contactPerson: "Jane Wangui",
    phone: "0729740142",
    whatsapp: "0729740142",
    email: "wangariorganics@gmail.com",
    county: "nairobi",
    subCounty: "Westlands",
    address: "Kangemi Market, off Waiyaki Way",
    productTypes: ["compost", "vermicompost"],
    description: {
      en: "We buy compost and vermicompost in bulk for landscaping clients and urban farmers in Nairobi. Minimum 200kg per delivery.",
      sw: "Tunanunua mboji na mboji ya minyoo kwa wingi kwa wateja wa mandhari na wakulima wa mjini Nairobi. Kilo 200 au zaidi kwa kila usafirishaji.",
    },
    priceRange: {
      en: "KSh 15-25 per kg depending on quality",
      sw: "KSh 15-25 kwa kilo kulingana na ubora",
    },
    isVerified: true,
    rating: 4.5,
    totalReviews: 23,
  },
  {
    businessName: "Muturi Gas & Energy",
    contactPerson: "Patrick Muturi",
    phone: "0734218905",
    whatsapp: "0734218905",
    email: "muturigas@gmail.com",
    county: "nairobi",
    subCounty: "Industrial Area",
    address: "Lunga Lunga Road, Industrial Area",
    productTypes: ["biogas_slurry", "bio_fertilizer"],
    description: {
      en: "We collect biogas slurry and package it as bio-fertilizer for retail. We need consistent weekly supply from farmers.",
      sw: "Tunakusanya tope la biogesi na kulifungasha kama mbolea ya kibiolojia kwa rejareja. Tunahitaji ugavi wa kila wiki kutoka kwa wakulima.",
    },
    priceRange: {
      en: "KSh 5-8 per liter of slurry",
      sw: "KSh 5-8 kwa lita ya tope",
    },
    isVerified: true,
    rating: 4.2,
    totalReviews: 15,
  },

  // Central Kenya
  {
    businessName: "Limuru Organic Growers",
    contactPerson: "Sarah Wanjiku",
    phone: "0729519805",
    whatsapp: "0729519805",
    county: "kiambu",
    subCounty: "Limuru",
    address: "Opposite Limuru Police Station",
    productTypes: ["compost", "vermicompost", "mulch"],
    description: {
      en: "A group of 40 organic vegetable farmers in Limuru looking for steady compost supply. We buy every month.",
      sw: "Kikundi cha wakulima 40 wa mboga za kikaboni Limuru wanaotafuta ugavi wa mboji wa kudumu. Tunanunua kila mwezi.",
    },
    priceRange: {
      en: "KSh 12-20 per kg",
      sw: "KSh 12-20 kwa kilo",
    },
    isVerified: true,
    rating: 4.7,
    totalReviews: 31,
  },
  {
    businessName: "Mbugua Farm Supplies",
    contactPerson: "Sam Mbugua",
    phone: "0734632451",
    whatsapp: "0734632451",
    county: "kiambu",
    subCounty: "Thika",
    address: "Thika Town, behind Makongeni Market",
    productTypes: ["compost", "animal_feed", "mulch"],
    description: {
      en: "Agro-vet shop buying treated maize stover and compost. We resell to small-scale farmers around Thika.",
      sw: "Duka la kilimo linalununua mashina ya mahindi yaliyotibiwa na mboji. Tunauza tena kwa wakulima wadogo karibu na Thika.",
    },
    priceRange: {
      en: "KSh 10-15 per kg compost, KSh 5-8 per kg treated stover",
      sw: "KSh 10-15 kwa kilo ya mboji, KSh 5-8 kwa kilo ya mashina yaliyotibiwa",
    },
    isVerified: true,
    rating: 4.0,
    totalReviews: 18,
  },

  // Rift Valley
  {
    businessName: "Kipchoge Energy Systems",
    contactPerson: "Amos Kipchoge",
    phone: "0722583091",
    whatsapp: "0722583091",
    email: "kipchogenergy@gmail.com",
    county: "nakuru",
    subCounty: "Nakuru Town East",
    address: "Lanet Road, near Egerton turn-off",
    productTypes: ["biogas_slurry", "bio_fertilizer"],
    description: {
      en: "Biogas facility buying cow dung and pig manure for energy production. We can collect from your farm daily.",
      sw: "Kituo cha biogesi kinachonunua kinyesi cha ng'ombe na nguruwe kwa uzalishaji wa nishati. Tunaweza kukusanya kutoka shambani kwako kila siku.",
    },
    priceRange: {
      en: "KSh 2-4 per kg fresh manure (we collect)",
      sw: "KSh 2-4 kwa kilo ya samadi safi (tunakusanya)",
    },
    isVerified: true,
    rating: 4.3,
    totalReviews: 27,
  },
  {
    businessName: "Chebet Dairy Feeds",
    contactPerson: "Mary Chebet",
    phone: "0724109876",
    whatsapp: "0724109876",
    county: "uasin_gishu",
    subCounty: "Eldoret East",
    address: "Uganda Road, Eldoret Town",
    productTypes: ["animal_feed", "silage"],
    description: {
      en: "Dairy farmers group buying silage and treated crop residues. We need large volumes especially during dry season.",
      sw: "Kikundi cha wafugaji wa maziwa kinachonunua silaji na mabaki ya mazao yaliyotibiwa. Tunahitaji kiasi kikubwa hasa wakati wa kiangazi.",
    },
    priceRange: {
      en: "KSh 8-12 per kg silage, KSh 5-8 per kg treated stover",
      sw: "KSh 8-12 kwa kilo ya silaji, KSh 5-8 kwa kilo ya mashina yaliyotibiwa",
    },
    isVerified: true,
    rating: 4.6,
    totalReviews: 22,
  },

  // Western Kenya
  {
    businessName: "Otieno & Sons Farm Produce",
    contactPerson: "Kevin Otieno",
    phone: "0711294857",
    whatsapp: "0711294857",
    county: "kisumu",
    subCounty: "Kisumu Central",
    address: "Oginga Odinga Street, Kisumu",
    productTypes: ["compost", "vermicompost"],
    description: {
      en: "We supply organic farmers around Kisumu with quality compost. Also helping farmers get organic certification.",
      sw: "Tunasambazia wakulima wa kikaboni karibu na Kisumu mboji bora. Pia tunasaidia wakulima kupata vyeti vya kikaboni.",
    },
    priceRange: {
      en: "KSh 15-22 per kg for certified organic compost",
      sw: "KSh 15-22 kwa kilo ya mboji ya kikaboni iliyoidhinishwa",
    },
    isVerified: true,
    rating: 4.4,
    totalReviews: 19,
  },
  {
    businessName: "Achieng Feeds Mill",
    contactPerson: "Rose Achieng",
    phone: "0728451036",
    whatsapp: "0728451036",
    county: "kisumu",
    subCounty: "Kisumu West",
    address: "Along Kisumu-Kakamega Road, past Mamboleo",
    productTypes: ["animal_feed", "silage"],
    description: {
      en: "Feed mill buying rice husks, maize bran, and silage for poultry and dairy feed. We buy all year round.",
      sw: "Kiwanda cha chakula cha mifugo kinachonunua maganda ya mpunga, pumba za mahindi, na silaji kwa chakula cha kuku na ng'ombe. Tunanunua mwaka mzima.",
    },
    priceRange: {
      en: "KSh 3-5 per kg rice husks, KSh 6-10 per kg silage",
      sw: "KSh 3-5 kwa kilo ya maganda ya mpunga, KSh 6-10 kwa kilo ya silaji",
    },
    isVerified: true,
    rating: 4.1,
    totalReviews: 14,
  },

  // Coast Region
  {
    businessName: "Omar Horticulture",
    contactPerson: "Hassan Abdalla",
    phone: "0738502914",
    whatsapp: "0738502914",
    email: "omarhorti@gmail.com",
    county: "mombasa",
    subCounty: "Mvita",
    address: "Mwembe Tayari, near Mombasa Town Hall",
    productTypes: ["compost", "mulch", "vermicompost"],
    description: {
      en: "We supply hotels and residential estates with organic compost for gardens. Good prices for quality product.",
      sw: "Tunasambazia hoteli na maeneo ya makazi mboji ya kikaboni kwa bustani. Bei nzuri kwa bidhaa bora.",
    },
    priceRange: {
      en: "KSh 20-30 per kg for premium compost",
      sw: "KSh 20-30 kwa kilo ya mboji bora",
    },
    isVerified: true,
    rating: 4.8,
    totalReviews: 12,
  },
  {
    businessName: "Kazungu Mixed Farming",
    contactPerson: "Bakari Kazungu",
    phone: "0720873416",
    whatsapp: "0720873416",
    county: "kilifi",
    subCounty: "Kilifi South",
    address: "Mtwapa-Kilifi Road, past Kilifi Bridge",
    productTypes: ["compost", "bio_fertilizer", "mulch"],
    description: {
      en: "Cashew and coconut farm that buys compost and mulch. We buy more during planting season, March-May.",
      sw: "Shamba la korosho na nazi linalununua mboji na vifuniko. Tunanunua zaidi wakati wa kupanda, Machi-Mei.",
    },
    priceRange: {
      en: "KSh 12-18 per kg",
      sw: "KSh 12-18 kwa kilo",
    },
    isVerified: false,
    rating: 4.0,
    totalReviews: 8,
  },

  // Mount Kenya Region
  {
    businessName: "Nyeri Hill Coffee Coop",
    contactPerson: "Francis Maina",
    phone: "0726381054",
    whatsapp: "0726381054",
    county: "nyeri",
    subCounty: "Nyeri Central",
    address: "Chaka Road, Nyeri Town",
    productTypes: ["compost", "vermicompost", "coffee_pulp_compost"],
    description: {
      en: "Coffee cooperative that buys compost for organic coffee farming. We also swap coffee pulp for finished compost.",
      sw: "Ushirika wa kahawa unaonunua mboji kwa kilimo cha kahawa ya kikaboni. Tunabadilishana maganda ya kahawa kwa mboji iliyokamilika.",
    },
    priceRange: {
      en: "KSh 18-25 per kg or pulp exchange",
      sw: "KSh 18-25 kwa kilo au kubadilishana maganda",
    },
    isVerified: true,
    rating: 4.5,
    totalReviews: 20,
  },
  {
    businessName: "Gitonga Agrovet",
    contactPerson: "Lucy Kagendo",
    phone: "0733147290",
    whatsapp: "0733147290",
    county: "meru",
    subCounty: "Meru Central",
    address: "Njuri Ncheke Street, Meru Town",
    productTypes: ["animal_feed", "compost", "silage"],
    description: {
      en: "Agrovet shop buying treated feeds and compost to sell to local farmers in Meru and Tharaka Nithi.",
      sw: "Duka la kilimo linalununua vyakula vilivyotibiwa na mboji kuuza kwa wakulima wa Meru na Tharaka Nithi.",
    },
    priceRange: {
      en: "KSh 8-15 per kg depending on product",
      sw: "KSh 8-15 kwa kilo kulingana na bidhaa",
    },
    isVerified: true,
    rating: 4.2,
    totalReviews: 16,
  },

  // Trans Nzoia / Kitale
  {
    businessName: "Wanyama Feeds & Grain",
    contactPerson: "Joseph Wanyama",
    phone: "0721056832",
    whatsapp: "0721056832",
    county: "trans_nzoia",
    subCounty: "Kitale",
    address: "Kitale Town, near Bongo Market",
    productTypes: ["animal_feed", "silage"],
    description: {
      en: "Animal feed producer buying maize stover and silage. We offer supply contracts for consistent sellers.",
      sw: "Mzalishaji wa chakula cha mifugo anayenunua mashina ya mahindi na silaji. Tunatoa mikataba kwa wauzaji wa kudumu.",
    },
    priceRange: {
      en: "KSh 4-7 per kg with contracts",
      sw: "KSh 4-7 kwa kilo na mikataba",
    },
    isVerified: true,
    rating: 4.4,
    totalReviews: 25,
  },

  // Machakos
  {
    businessName: "Mutua Green Farm",
    contactPerson: "Catherine Nduku",
    phone: "0725690341",
    whatsapp: "0725690341",
    county: "machakos",
    subCounty: "Machakos Town",
    address: "Machakos Town, behind KCB Bank",
    productTypes: ["compost", "bio_fertilizer"],
    description: {
      en: "Social enterprise helping farmers in Ukambani with organic inputs. Fair prices and we also do free training.",
      sw: "Biashara ya kijamii inayosaidia wakulima wa Ukambani na pembejeo za kikaboni. Bei za haki na pia tunatoa mafunzo bure.",
    },
    priceRange: {
      en: "KSh 12-18 per kg plus training support",
      sw: "KSh 12-18 kwa kilo pamoja na msaada wa mafunzo",
    },
    isVerified: true,
    rating: 4.6,
    totalReviews: 21,
  },

  // Kajiado
  {
    businessName: "Nchoe Livestock Feeds",
    contactPerson: "Daniel Nchoe",
    phone: "0737410285",
    whatsapp: "0737410285",
    county: "kajiado",
    subCounty: "Kajiado Central",
    address: "Kajiado Town, next to Isinya Road junction",
    productTypes: ["animal_feed", "silage", "mulch"],
    description: {
      en: "Cattle ranch buying supplementary feeds and fodder. During drought we buy anything available.",
      sw: "Shamba la ng'ombe linalununua vyakula vya ziada na lishe. Wakati wa ukame tunanunua chochote kinachopatikana.",
    },
    priceRange: {
      en: "KSh 6-10 per kg",
      sw: "KSh 6-10 kwa kilo",
    },
    isVerified: false,
    rating: 3.9,
    totalReviews: 11,
  },
];
