// Buyer seed data for marketplace
export const buyerSeedData = [
  // Nairobi Region
  {
    businessName: "Green Gold Organics",
    contactPerson: "John Mwangi",
    phone: "+254712345678",
    whatsapp: "+254712345678",
    email: "info@greengold.co.ke",
    county: "nairobi",
    subCounty: "Westlands",
    address: "Westlands Business Park, Nairobi",
    productTypes: ["compost", "vermicompost"],
    description: {
      en: "Premium organic compost buyer for urban gardens and landscaping companies. We buy in bulk (minimum 500kg).",
      sw: "Mnunuzi wa mboji bora ya kikaboni kwa bustani za mjini na makampuni ya mandhari. Tunanunua kwa wingi (kilo 500 au zaidi).",
    },
    priceRange: {
      en: "KSh 15-25 per kg depending on quality",
      sw: "KSh 15-25 kwa kilo kulingana na ubora",
    },
    isVerified: true,
    rating: 4.5,
    totalReviews: 23,
  },
  {
    businessName: "Safari Biogas Solutions",
    contactPerson: "Grace Wanjiku",
    phone: "+254723456789",
    whatsapp: "+254723456789",
    email: "sales@safaribiogas.co.ke",
    county: "nairobi",
    subCounty: "Industrial Area",
    address: "Enterprise Road, Industrial Area",
    productTypes: ["biogas_slurry", "bio_fertilizer"],
    description: {
      en: "We purchase biogas slurry and convert it to packaged bio-fertilizer for retail. Consistent supply needed.",
      sw: "Tunanunua tope la biogesi na kulibadilisha kuwa mbolea ya kibiolojia iliyofungashwa kwa rejareja. Ugavi wa kudumu unahitajika.",
    },
    priceRange: {
      en: "KSh 5-8 per liter of slurry",
      sw: "KSh 5-8 kwa lita ya tope",
    },
    isVerified: true,
    rating: 4.2,
    totalReviews: 15,
  },

  // Central Kenya
  {
    businessName: "Kiambu Organic Farms Coop",
    contactPerson: "Peter Kamau",
    phone: "+254734567890",
    whatsapp: "+254734567890",
    county: "kiambu",
    subCounty: "Limuru",
    address: "Limuru Town Center",
    productTypes: ["compost", "vermicompost", "mulch"],
    description: {
      en: "Cooperative of 50+ organic farmers seeking quality compost for vegetable production. Regular buyer.",
      sw: "Ushirika wa wakulima 50+ wa kikaboni wanaotafuta mboji bora kwa uzalishaji wa mboga. Mnunuzi wa kawaida.",
    },
    priceRange: {
      en: "KSh 12-20 per kg",
      sw: "KSh 12-20 kwa kilo",
    },
    isVerified: true,
    rating: 4.7,
    totalReviews: 31,
  },
  {
    businessName: "Thika Farm Supplies",
    contactPerson: "Samuel Njoroge",
    phone: "+254745678901",
    whatsapp: "+254745678901",
    county: "kiambu",
    subCounty: "Thika",
    address: "Thika Town, Near Market",
    productTypes: ["compost", "animal_feed", "mulch"],
    description: {
      en: "Agricultural supplies shop buying treated maize stover and compost for resale to local farmers.",
      sw: "Duka la vifaa vya kilimo linalununua mashina ya mahindi yaliyotibiwa na mboji kwa kuuza tena kwa wakulima wa ndani.",
    },
    priceRange: {
      en: "KSh 10-15 per kg compost, KSh 5-8 per kg treated stover",
      sw: "KSh 10-15 kwa kilo ya mboji, KSh 5-8 kwa kilo ya mashina yaliyotibiwa",
    },
    isVerified: true,
    rating: 4.0,
    totalReviews: 18,
  },

  // Rift Valley
  {
    businessName: "Nakuru Green Energy",
    contactPerson: "James Korir",
    phone: "+254756789012",
    whatsapp: "+254756789012",
    email: "info@nakurugreen.co.ke",
    county: "nakuru",
    subCounty: "Nakuru Town East",
    address: "Nakuru Industrial Park",
    productTypes: ["biogas_slurry", "bio_fertilizer"],
    description: {
      en: "Large-scale biogas facility buying cow dung and pig manure for energy production. Daily collection available.",
      sw: "Kituo kikubwa cha biogesi kinachonunua kinyesi cha ng'ombe na nguruwe kwa uzalishaji wa nishati. Ukusanyaji wa kila siku unapatikana.",
    },
    priceRange: {
      en: "KSh 2-4 per kg fresh manure (we collect)",
      sw: "KSh 2-4 kwa kilo ya samadi safi (tunakusanya)",
    },
    isVerified: true,
    rating: 4.3,
    totalReviews: 27,
  },
  {
    businessName: "Eldoret Dairy Feeds",
    contactPerson: "Mary Chemutai",
    phone: "+254767890123",
    whatsapp: "+254767890123",
    county: "uasin_gishu",
    subCounty: "Eldoret East",
    address: "Eldoret Town",
    productTypes: ["animal_feed", "silage"],
    description: {
      en: "Dairy farmers cooperative buying silage and treated crop residues. Large volumes needed during dry season.",
      sw: "Ushirika wa wafugaji wa ng'ombe wa maziwa unaonunua silaji na mabaki ya mazao yaliyotibiwa. Kiasi kikubwa kinahitajika wakati wa msimu wa kiangazi.",
    },
    priceRange: {
      en: "KSh 8-12 per kg silage, KSh 5-8 per kg treated stover",
      sw: "KSh 8-12 kwa kilo ya silaji, KSh 5-8 kwa kilo ya mashina yaliyotibiwa",
    },
    isVerified: true,
    rating: 4.6,
    totalReviews: 22,
  },

  // Western Kenya
  {
    businessName: "Kisumu Organic Markets",
    contactPerson: "Otieno Ochieng",
    phone: "+254778901234",
    whatsapp: "+254778901234",
    county: "kisumu",
    subCounty: "Kisumu Central",
    address: "Kisumu City Market Area",
    productTypes: ["compost", "vermicompost"],
    description: {
      en: "Organic produce market seeking quality compost for our partner farmers. Certification assistance available.",
      sw: "Soko la mazao ya kikaboni linlotafuta mboji bora kwa wakulima wetu washirika. Msaada wa vyeti unapatikana.",
    },
    priceRange: {
      en: "KSh 15-22 per kg for certified organic compost",
      sw: "KSh 15-22 kwa kilo ya mboji ya kikaboni iliyoidhinishwa",
    },
    isVerified: true,
    rating: 4.4,
    totalReviews: 19,
  },
  {
    businessName: "Lake Region Feeds",
    contactPerson: "Rose Akinyi",
    phone: "+254789012345",
    whatsapp: "+254789012345",
    county: "kisumu",
    subCounty: "Kisumu West",
    address: "Along Kisumu-Kakamega Road",
    productTypes: ["animal_feed", "silage"],
    description: {
      en: "Feed mill buying rice husks, maize bran, and quality silage for poultry and dairy feed production.",
      sw: "Kiwanda cha chakula cha mifugo kinachonunua maganda ya mpunga, pumba za mahindi, na silaji bora kwa uzalishaji wa chakula cha kuku na ng'ombe.",
    },
    priceRange: {
      en: "KSh 3-5 per kg rice husks, KSh 6-10 per kg silage",
      sw: "KSh 3-5 kwa kilo ya maganda ya mpunga, KSh 6-10 kwa kilo ya silaji",
    },
    isVerified: true,
    rating: 4.1,
    totalReviews: 14,
  },

  // Coast Region
  {
    businessName: "Mombasa Horticulture Supplies",
    contactPerson: "Hassan Omar",
    phone: "+254790123456",
    whatsapp: "+254790123456",
    email: "mhsupplies@gmail.com",
    county: "mombasa",
    subCounty: "Mvita",
    address: "Mombasa Town, Near Port",
    productTypes: ["compost", "mulch", "vermicompost"],
    description: {
      en: "Supplying hotels and resorts with organic compost for landscaping. Premium prices for quality product.",
      sw: "Kusambaza hoteli na mapumziko na mboji ya kikaboni kwa mandhari. Bei za juu kwa bidhaa bora.",
    },
    priceRange: {
      en: "KSh 20-30 per kg for premium compost",
      sw: "KSh 20-30 kwa kilo ya mboji bora",
    },
    isVerified: true,
    rating: 4.8,
    totalReviews: 12,
  },
  {
    businessName: "Kilifi Eco Farms",
    contactPerson: "Fatma Bakari",
    phone: "+254701234567",
    whatsapp: "+254701234567",
    county: "kilifi",
    subCounty: "Kilifi South",
    address: "Kilifi Town",
    productTypes: ["compost", "bio_fertilizer", "mulch"],
    description: {
      en: "Organic cashew and coconut farm buying compost and mulching materials. Seasonal buyer.",
      sw: "Shamba la korosho na nazi la kikaboni linalununua mboji na vifaa vya kufunika. Mnunuzi wa msimu.",
    },
    priceRange: {
      en: "KSh 12-18 per kg",
      sw: "KSh 12-18 kwa kilo",
    },
    isVerified: false,
    rating: 4.0,
    totalReviews: 8,
  },

  // Mount Kenya Region
  {
    businessName: "Nyeri Coffee Farmers Coop",
    contactPerson: "Paul Maina",
    phone: "+254712098765",
    whatsapp: "+254712098765",
    county: "nyeri",
    subCounty: "Nyeri Central",
    address: "Nyeri Town",
    productTypes: ["compost", "vermicompost", "coffee_pulp_compost"],
    description: {
      en: "Coffee cooperative buying quality compost for organic coffee production. Can trade coffee pulp for finished compost.",
      sw: "Ushirika wa kahawa unaonunua mboji bora kwa uzalishaji wa kahawa ya kikaboni. Tunaweza kubadilishana maganda ya kahawa kwa mboji iliyokamilika.",
    },
    priceRange: {
      en: "KSh 18-25 per kg or pulp exchange",
      sw: "KSh 18-25 kwa kilo au kubadilishana maganda",
    },
    isVerified: true,
    rating: 4.5,
    totalReviews: 20,
  },
  {
    businessName: "Meru Agrovet",
    contactPerson: "Michael Mwiti",
    phone: "+254723098765",
    whatsapp: "+254723098765",
    county: "meru",
    subCounty: "Meru Central",
    address: "Meru Town Center",
    productTypes: ["animal_feed", "compost", "silage"],
    description: {
      en: "Agricultural shop buying various farm products including treated feeds and compost for retail.",
      sw: "Duka la kilimo linalununua bidhaa mbalimbali za shamba ikiwa ni pamoja na vyakula vilivyotibiwa na mboji kwa rejareja.",
    },
    priceRange: {
      en: "KSh 8-15 per kg depending on product",
      sw: "KSh 8-15 kwa kilo kulingana na bidhaa",
    },
    isVerified: true,
    rating: 4.2,
    totalReviews: 16,
  },

  // Trans Nzoia / Kitale
  {
    businessName: "Kitale Maize Processors",
    contactPerson: "Joseph Wanyama",
    phone: "+254734098765",
    whatsapp: "+254734098765",
    county: "trans_nzoia",
    subCounty: "Kitale",
    address: "Kitale Town Industrial Area",
    productTypes: ["animal_feed", "silage"],
    description: {
      en: "Large-scale animal feed producer buying maize stover and silage. Consistent supply contracts available.",
      sw: "Mzalishaji mkubwa wa chakula cha mifugo anayenunua mashina ya mahindi na silaji. Mikataba ya ugavi wa kudumu inapatikana.",
    },
    priceRange: {
      en: "KSh 4-7 per kg with contracts",
      sw: "KSh 4-7 kwa kilo na mikataba",
    },
    isVerified: true,
    rating: 4.4,
    totalReviews: 25,
  },

  // Machakos
  {
    businessName: "Machakos Green Solutions",
    contactPerson: "Catherine Mueni",
    phone: "+254745098765",
    whatsapp: "+254745098765",
    county: "machakos",
    subCounty: "Machakos Town",
    address: "Machakos Town",
    productTypes: ["compost", "bio_fertilizer"],
    description: {
      en: "Social enterprise supporting local farmers with organic inputs. Fair prices and training included.",
      sw: "Biashara ya kijamii inayosaidia wakulima wa ndani na pembejeo za kikaboni. Bei za haki na mafunzo yanajumuishwa.",
    },
    priceRange: {
      en: "KSh 12-18 per kg plus training support",
      sw: "KSh 12-18 kwa kilo pamoja na msaada wa mafunzo",
    },
    isVerified: true,
    rating: 4.6,
    totalReviews: 21,
  },

  // Kajiado
  {
    businessName: "Maasai Organic Ranches",
    contactPerson: "Daniel Ole Parsitau",
    phone: "+254756098765",
    whatsapp: "+254756098765",
    county: "kajiado",
    subCounty: "Kajiado Central",
    address: "Kajiado Town",
    productTypes: ["animal_feed", "silage", "mulch"],
    description: {
      en: "Cattle ranch buying supplementary feeds and fodder, especially during drought periods.",
      sw: "Shamba la ng'ombe linalununua vyakula vya ziada na lishe, hasa wakati wa ukame.",
    },
    priceRange: {
      en: "KSh 6-10 per kg",
      sw: "KSh 6-10 kwa kilo",
    },
    isVerified: false,
    rating: 3.9,
    totalReviews: 11,
  },
];
